apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: deployment-workflow
  namespace: argo
spec:
  entrypoint: deploy-app
  templates:
  - name: deploy-app
    steps:
    - - name: apply-deployment
        template: kubectl-apply
        arguments:
          parameters:
          - name: manifest
            value: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: my-app
              spec:
                replicas: 2
                selector:
                  matchLabels:
                    app: my-app
                template:
                  metadata:
                    labels:
                      app: my-app
                  spec:
                    containers:
                    - name: my-app-container
                      image: nginx:latest
                      ports:
                      - containerPort: 80

    - - name: apply-service
        template: kubectl-apply
        arguments:
          parameters:
          - name: manifest
            value: |
              apiVersion: v1
              kind: Service
              metadata:
                name: my-app-service
              spec:
                selector:
                  app: my-app
                ports:
                - protocol: TCP
                  port: 80
                  targetPort: 80
                type: ClusterIP  # Changed from LoadBalancer to ClusterIP

  - name: kubectl-apply
    inputs:
      parameters:
      - name: manifest
    container:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      args: ["echo \"{{inputs.parameters.manifest}}\" | kubectl apply -f -"]
