# hello-world-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo Hello, World!"]
