apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: bp-container-template-wf

  #namespace: argo
spec:
  entrypoint: container-template
  templates:
    - name: container-template
      container:
        image: python:3.8-slim
        args: [echo, "print('hi team, this workflow for container templates')"]
